export const NOTIFICATION_TYPES = {
  BID_PLACED: 'BID_PLACED',
  NEGOTIATION_PLACED: 'NEGOTIATION_PLACED',
  ITEM_SOLD: 'ITEM_SOLD',
  PURCHASE_SUCCESS: 'PURCHASE_SUCCESS',
  SCHEDULE_CHANGED: 'SCHEDULE_CHANGED',
  ITEM_FAVORITED: 'ITEM_FAVORITED'
}; 